### PR TITLE
Fix maven issue, support windows OS and support debug environment

### PR DESCRIPTION
**Pull request by michaelmao999**
1. Correct the version issue on maven config file.
2. Fix some bugs to allow RocksDB running on windows OS.
3. Fix SpringBoot related issue that provide the ability to debug gateway on IDEA with product config file

### CODE REVIEW

**Comment by zhangshuang01** [comment]
Tests in RocksDBStorageTest.java still failed in windows env.
I use your bat files cannot start the peers, could you tell me how to use them?
@michaelmao999

**Comment by imuge** [comment]
Tests in RocksDBStorageTest.java still failed in windows env.
I use your bat files cannot start the peers, could you tell me how to use them?
@michaelmao999

**Comment by michaelmao999** [comment]
Please initialize blockchain ledger prior to start peer node.  
For detail, please refer to http://ledger.jd.com/setup.html

**Comment by huanghaiquan** [comment]
Thanks for your committing!  We have solved this issue in the latest version.  
For further communication  please email us to jdchain-support@jd.com.

**Pull request closed without merging**
